version: '3.9'

services:

  server:
    container_name: kinopoisk_server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - kinopoisk_network

  postgres:
    container_name: kinopoisk_db
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kinopoisk_network

volumes:
  postgres_data:

networks:
  kinopoisk_network:
    driver: bridge
